name: churn-imbalanced-dvc
on: [push]
permissions: write-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1



      - name: Prepare Environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup DVC
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive-service-account.json
          dvc remote modify myremote gdrive_service_account_json_file gdrive-service-account.json
          dvc pull
          python main.py
          # dvc add ./data/ ./models/
          # dvc push

      - name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Get the report
          echo "## Metrics" > report.md
          # cat metrics.txt >> report.md
          
          awk 'NR%4{print "    " $0}{print ""}' metrics.txt >> report.md

          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md
          cml comment create report.md
